### ISSUE TITLE
Code Example Play doesn't work

### ISSUE THREAD

**Issue by FiireWiinter** [toxicrecker/DiscordUtils#7]
When i try to run the play command from the code example of the music system, i get following errors

with a seach query
`ERROR: query "crab rave": Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)'))
Ignoring exception in command play:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\Users\admin\Desktop\Python Code\test.py", line 22, in play
    await player.queue(url, search=True)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\DiscordUtils\Music.py", line 171, in queue
    song = await get_video_data(url, search, bettersearch, self.loop)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\DiscordUtils\Music.py", line 70, in get_video_data
    data = data["entries"][0]
TypeError: 'NoneType' object is not subscriptable`

with a direct video link
`ERROR: No video formats found
Ignoring exception in command play:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\Users\admin\Desktop\Python Code\test.py", line 22, in play
    await player.queue(url, search=True)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\DiscordUtils\Music.py", line 171, in queue
    song = await get_video_data(url, search, bettersearch, self.loop)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\DiscordUtils\Music.py", line 70, in get_video_data
    data = data["entries"][0]
TypeError: 'NoneType' object is not subscriptable`

**Comment by toxicrecker** [comment]
Its a youtube-dl problem, use bettersearch instead of search and it'll fix it
